### ISSUE TITLE
Freezing with react navigation bottom-tabs

### ISSUE THREAD

**Issue by tedi** [software-mansion/react-freeze#3] opened 2021-10-29 21:06 UTC
Thank you for your work with this library, very excited to put it in production.

While testing things out almost everything seemed to work smoothly, with the exception of react navigation bottom-tabs. We noticed this specifically on screens with media playing. We have a state update that fires on navigation blur. The media then adjusts play state when that happens. This works as expected when navigating within the same tab. 

However when switching tabs, we ran into some issues. The state does not update on time, causing the media to be frozen in a playing state when navigating to a different tab. The blur event seems to fire appropriately, so my guess is that the previous tab is freezing almost immediately, not allowing side effects. 

Currently running the latest version of all react-navigation libraries and RN 0.64.1

Would love any feedback on dealing with this scenario.

Thanks,
Tedi

**Comment by WoLewicki** [comment] 2021-11-02 08:55
@tedi could you provide a repo or a code snippet with minimal configuration needed to reproduce the issue?

**Comment by tedi** [comment] 2021-11-03 23:11
@WoLewicki will do in the next few days. Thanks.

**Comment by kacperkapusciak** [comment] 2021-11-16 08:02
@tedi 🏓

**Comment by kacperkapusciak** [comment] 2021-12-13 15:44
I'm closing this issue because it looks like this problem was explained in detail in https://github.com/software-mansion/react-native-screens/issues/1198,

fixed in https://github.com/software-mansion/react-native-screens/pull/1220,

and released in [react-native-screens v3.10.0](https://github.com/software-mansion/react-native-screens/releases/tag/3.10.0) :tada:

**Closed by kacperkapusciak** 2021-12-13 15:44 UTC
